### ISSUE TITLE
项目没开发完吧？

### ISSUE THREAD

**Issue by Tyrone-Zhao** [csunny/py-bitcoin#8]
架构功能实现了吗？不可能就这么点代码吧？能部署试一下吗？可以的话去订阅专栏

**Comment by csunny** [comment]
@Tyrone-Zhao   是的，没开发完，只是实现了一部分。 目前看到的也是几个核心模块的实现与单元测试，由于个人工作原因，没时间开发，所以后面一直拖着。 另外，专栏里面只是引用了此项目中的某些模块，比如base58，merkerTree，椭圆加密等等，两者不是一回事。
